@startuml

actor Admin
participant "System" as System
participant "Database" as DB

Admin -> System: Memasukkan Data Barang
System -> DB: Menginput data barang

alt Jika valid
    System -> System: Memastikan stok barang masih ada
    DB -> Admin: Menampilkan barang yang hampir habis

else Jika tidak valid
    DB -> System: Kode barang sudah terpakai
    System -> Admin: Notifikasi kode barang sudah terpakai
end

@enduml