@startuml

actor Customers
participant "Pembelian" as Pembelian
participant "Database" as DB

Customers -> Pembelian: Membeli barang yang diinginkan
Pembelian -> DB: Mengecek ketersediaan barang

alt Jika Valid
    Pembelian -> Customers: Barang tersedia, lanjutkan pembayaran
    Customers -> Pembelian: Melakukan pembayaran
    Pembelian -> DB: Mengonfirmasi pembayaran
    DB -> Pembelian: Pembayaran diterima
    Pembelian -> Customers: Pembayaran berhasil, barang disiapkan

else Jika tidak Valid
    DB -> Pembelian: Barang tidak tersedia
    Pembelian -> Customers: Pembelian gagal, barang tidak tersedia
end

@enduml
