@startuml

actor Sales
participant "Pengeluaran" as pengeluaran
participant "Database" as DB

Sales -> pengeluaran: Input pengeluaran bulanan
pengeluaran -> pengeluaran: Memproses pengeluaran dadakan

alt Data valid
    pengeluaran -> DB: Menginput data pengeluaran
    DB -> pengeluaran: Data berhasil disimpan
    pengeluaran -> Sales: Pengeluaran berhasil dicatat

else Data tidak valid
    DB -> pengeluaran: Terjadi kesalahan data
    pengeluaran -> Sales: Terjadi kesalahan data
end

@enduml
