@startuml

actor Sales
participant "Penghasilan" as hasil
participant "Database" as DB
participant "Customer" as pembeli

pembeli -> DB: Membeli barang
DB -> Sales: Notifikasi pembelian

alt Jika pembayaran valid
    Sales -> hasil: Pesanan diterima
    hasil -> hasil: Menyiapkan pesanan dan memastikan pembayaran
    hasil -> DB: Menginput data penghasilan
    DB -> Sales: Data penghasilan tercatat

else Jika pembayaran tidak valid
    DB -> hasil: Pembayaran belum dilakukan
    hasil -> Sales: Menahan barang / Menghubungi pembeli
    Sales -> pembeli: Pembeli membayar utang
    pembeli -> DB: Melakukan pembayaran
    DB -> Sales: Pembayaran dikonfirmasi
end

@enduml