@startuml

actor Admin
participant Rekap
participant "Database" as DB
participant Penghasilan
participant Pengeluaran

Penghasilan -> DB: Memasukkan data penghasilan
Pengeluaran -> DB: Memasukkan data pengeluaran

alt Jika valid
    Admin -> Rekap: Merekap data penghasilan dan pengeluaran
    Rekap -> DB: Mengambil data penghasilan dan pengeluaran
    Rekap -> Rekap: Menghitung penghasilan kotor
    Rekap -> Rekap: Menghitung penghasilan bersih (penghasilan kotor - pengeluaran)
    Rekap -> Admin: Menampilkan penghasilan kotor dan bersih

else Jika tidak valid
    Rekap -> DB: Gagal mengambil data penghasilan/pengeluaran
    DB -> Rekap: Data penghasilan atau pengeluaran tidak valid
    Rekap -> Admin: Error, data penghasilan/pengeluaran tidak valid
end

@enduml